name: Generate Table of Contents

on: push

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          COMMIT_MESSAGE: "📖 Update Table of Contents"
          COMMIT_NAME: "${github.workflow}"
